name: CI

on:
  release:
    types:
      - created

jobs:
  nuget:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Setup .NET environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0'

      - name: Build project
        run: dotnet build -c Release
        
      - name: Test project
        run: dotnet test

      - name: Generate a NuGet package
        run: dotnet pack --no-build -c Release -o .
        
      - name: Push to GitHub package registry
        run: dotnet nuget push *.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_AUTH_TOKEN
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_TOKEN}}
